name: freelancer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.0
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.8
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.1
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  provider: ^6.0.5
  uuid: ^3.0.7
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.1.2

flutter:

  uses-material-design: true

  assets:
    - images/


  fonts:
    - family: signatra
      fonts:
        - asset: fonts/Signatra.ttf
  